### ISSUE TITLE
What does Assignment mean?

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#144]
What does Assignment mean? Number of columns? If so "N columns" would be clearer.
Screen Shot 2017-07-06 at 10.54.08 PM

**Comment by rminnett** [comment]
I presume you mean this "Assignment"? 
![image](https://user-images.githubusercontent.com/1182698/27983520-e4a265b8-6372-11e7-823c-1c4c8a875e77.png)

If so, yes, perhaps it's not the best description. This is because "N Rows" refers to the number of rows in the table in the contribution, but not the number of "Sites", for example, that they are assigned to. It's possible to have the same number of rows but change the number of unique site names in a contribution so I was trying to make this more clear. Would "N Names" be more clear? Let me know if you think of a better way of describing this. 

I could also calculate difference statistics to show the change rather than the before and after. For example: "+3 Site Rows, -2 Site Names".
