### ISSUE TITLE
Delayed indexing does not finish

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#335]
Luke Fairchild's latest contribution has been queued for indexing for over an hour and all of the sub tables are not available. Locations through specimens. Maybe he did not have a location table?
<img width="1240" alt="screen shot 2018-04-11 at 5 40 13 am" src="https://user-images.githubusercontent.com/1278789/38617059-dbe90b4a-3d4a-11e8-99a2-c4dbfd499c19.png">

**Comment by rminnett** [comment]
I think this contribution got stuck in a strange state because of possibly being created before the last deployment but activated afterward. I reprocessed this one manually, so it should be properly indexed now. This could theoretically happen to other contributions, so if you see it again, I can reprocess the ones with issues.
