### ISSUE TITLE
For doi reference lookups, "doi" works but "DOI" adds an extra slash and fails

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#336]
For doi reference lookups, "doi" works but "DOI" adds an extra slash.
So: https://earthref.org/MagIC/DOI/10.1002/2017GC007318
Gives this:
<img width="1263" alt="screen shot 2018-04-16 at 12 21 30 am" src="https://user-images.githubusercontent.com/1278789/38795251-76558022-410c-11e8-852a-fa54ef71f729.png">

While: https://earthref.org/MagIC/doi/10.1002/2017GC007318
Is correct with this:
<img width="1273" alt="screen shot 2018-04-16 at 12 21 49 am" src="https://user-images.githubusercontent.com/1278789/38795294-92a6ad78-410c-11e8-9cae-9fa34593c46c.png">

As people are putting these links in journals for reference, it would be great to get this worked out quickly. Thanks.

**Comment by rminnett** [comment]
Since these URLs are getting processed on the earthref.org server first, it usually adds a slash to the end to normalize the URL before testing the routing rules. I had made an exception for the "doi" case, but it was case-sensitive. Now the "doi" can either be lower or upper case:

https://earthref.org/MagIC/DOI/10.1002/2017GC007318
https://earthref.org/MagIC/doi/10.1002/2017GC007318

But not:

https://earthref.org/MagIC/Doi/10.1002/2017GC007318
