### ISSUE TITLE
Fields in the search interface are case-sensitive

### ISSUE THREAD

**Issue by moonshoes87** [earthref/MagIC#348]
In the search interface, at least some of the fields appear to be case-sensitive.  So for example under Location Type, I can select Region (642) or region (8).  Is this the desired behavior?

**Comment by rminnett** [comment]
Yes, Elasticsearch indexes the data in the contribution with the case intact. Since the controlled vocabularies are case-sensitive, too, "region" would fail the validation for the "Location Type" controlled vocabulary. Ideally, the "region" entries should never have been allowed in, but, at least in this case, fixing data with only minor differences (case and one or two typos) compared to values in the controlled vocabularies is relatively to easy to fix programmatically.

**Comment by rminnett** [comment]
This turns out to be valuable in identifying contributions with issues. We can implement the case-insensitive filter buckets later if necessary.
