### ISSUE TITLE
Plot not circular when it should be

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#438]
The first contribution on the homepage(Greve and Turner 2017) now has a plot that is elipictal instead of circular. Bono 2019 also has this problem. But Bogue2017 and Trindade2018 don't. 
![screen shot 2019-02-19 at 10 35 35 pm](https://user-images.githubusercontent.com/1278789/53071315-b51fa700-3496-11e9-8117-668da37cd174.png)

**Comment by rminnett** [comment]
That's because it's trying to squeeze the full plot into 100px wide thumbnails and some of the equal area plots appear to have more horizontal padding that others. I mentioned in https://github.com/PmagPy/PmagPy/issues/515 that if it's too tricky to crop thumbnails, I can try to do this in the browser for now with a set of rules for different plot types.
