### ISSUE TITLE
static.earthref.org Certificate name mismatch 

### ISSUE THREAD

**Issue by valentinedwv** [earthref/MagIC#439]
https://www.ssllabs.com/ssltest/analyze.html?d=static.earthref.org

Would like to use some old links as browse graphics for metadata records

https://static.earthref.org/imcache/Set(gravity:Center)\|Crop(geometry:360x360+10+0)\|Resize(geometry:100x100)/images/MAGIC/static_plots/11169/LO:_Khukh_Davaa_SI:_Z33_SA:_Z33.8_SP:_Z33.8a_CO:_g_TY:_demag_.png

**Comment by rminnett** [comment]
Hi David, those link to an old server and we're not currently using the "static" subdomain so it hasn't been included in our SSL certificate. There's no guarantee any of those files will persist in the future, but if they do still exist, they should be accessible with the main earthref.org domain. For example:

https://earthref.org/imcache/Crop(geometry:292x292+111+104)%7cResize(geometry:100x100)/images/MAGIC/static_plots/7738/LO:_Valles%20Caldera_SI:__SA:__SP:__CO:_g_TY:_eqarea_.png

instead of:

https://static.earthref.org/imcache/Crop(geometry:292x292+111+104)%7cResize(geometry:100x100)/images/MAGIC/static_plots/7738/LO:_Valles%20Caldera_SI:__SA:__SP:__CO:_g_TY:_eqarea_.png

Now we're serving those images proxied from S3 through our web app, so you can't reach the plot files directly with a URL, and the maps are coming directly from Google. If you want access to plot thumbnails and full-size plots and you have an AWS canonical ID or email address we can give you read access to the bucket (your account would pay for the throughput).
