### ISSUE TITLE
Back button on plots should close the plots screen, not go back in the background on the browser

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#444]
Back button on plots should close the plots screen, not go back in the background on the browser. People (I still do) will expect that back will close the plot screen and go back to the main one (In their mind the previous screen). Pressing the "x" should not be necessary (if easily done).

**Comment by rminnett** [comment]
This is a bit tricky, but not impossible. Showing the plots is actually just a change in the state of the plot thumbnail in the summary you clicked on. It's the same problems as changing tabs in the search interface and expecting the back button to go to the previous tab instead of leaving the search interface. I can see this would be preferable, though.

**Comment by njarboe** [comment]
I guess this is expected in the world of web apps. People will be used to it by now hopefully.
