### ISSUE TITLE
complicated .xlsx file does not import

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#51]
Same data as last issue but in this case the import displays no data.

[Table_4_PaleoMagData.xlsx](https://github.com/earthref/MagIC/files/914478/Table_4_PaleoMagData.xlsx)
![screen shot 2017-04-11 at 12 45 29 pm](https://cloud.githubusercontent.com/assets/1278789/24927734/db433400-1eb4-11e7-9447-3b93ee7c0c62.png)

**Comment by rminnett** [comment]
Should we support such an upload? That file appears to have been copied and pasted from a PDF or other document and has merged cells, line breaks in cells, long hyphens instead of negative signs, etc. Perhaps when we enable online editing again, it'll be easier to let the user clean it up after upload and we should try to allow messy copy and paste or Excel files like this.

**Comment by njarboe** [comment]
Now working
