### ISSUE TITLE
Publication link should link to the where the paper is hosted at the journal site, not to MagIC

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#91]

**Comment by rminnett** [comment]
This is supposed to query MagIC using the publication DOI, which could return all of the versions that were uploaded for that DOI (and then optionally limited to the latest version once I add that filter), rather than a specific version when querying by MagIC contribution ID. The previous versions aren't indexed yet (they're only in the version history when expanding a contribution result), so there's currently no difference in the results.

Would it be more useful to no have a link to publication (as you expected) instead of a link to query MagIC with the DOI?

**Comment by njarboe** [comment]
Since we have a one to one correspondence between publication DOI and MagIC data set (with versions) and the current links go to the same page, I'm not sure we need to display the MagIC DOI link. If you go to a magic link and it is not the most recent, it should show the list and highlight the one linked to so people are very aware they are not getting the most updated version. A link to the publication would be very useful as scientists will want to read the paper on any data they are using.

Also, why do you think the first search paper (Weiss et al. (2017)) does not have a publication link even though it has 3 versions. At quick glance it looks like one version, no pub link, multiple version, pub link. Except the first one.
